services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak-probabilidad
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      # - ../frontend/themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network

  quarkus-probabilidad:
    build: ../backend
    container_name: quarkus-probabilidad
    restart: unless-stopped
    environment:
      QUARKUS_OIDC_AUTH_SERVER_URL: ${QUARKUS_OIDC_AUTH_SERVER_URL}
      QUARKUS_OIDC_CLIENT_ID: ${QUARKUS_OIDC_CLIENT_ID}
      QUARKUS_OIDC_APP_TYPE: ${QUARKUS_OIDC_APP_TYPE}
      QUARKUS_OIDC_AUDIENCE: ${QUARKUS_OIDC_AUDIENCE}
      QUARKUS_OIDC_ROLES_SOURCE: ${QUARKUS_OIDC_ROLES_SOURCE}
      QUARKUS_OIDC_ROLE_PATH: ${QUARKUS_OIDC_ROLE_PATH}
      ADMIN_URL: ${ADMIN_URL}
      REALM: ${REALM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      QUARKUS_PUBLIC_PATHS: ${QUARKUS_PUBLIC_PATHS}
      QUARKUS_HTTP_CORS: ${QUARKUS_HTTP_CORS}
      QUARKUS_HTTP_CORS_ORIGINS: ${QUARKUS_HTTP_CORS_ORIGINS}
      QUARKUS_HTTP_CORS_METHODS: ${QUARKUS_HTTP_CORS_METHODS}
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - app-network

  quizdb:
    image: postgres:latest
    container_name: postgres-quiz
    restart: always
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - quizdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz -d quizdb"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-network

volumes:
  quizdb-data:
  kc-data:

networks:
  app-network:
    driver: bridge
