services:
  # Base de Datos PostgreSQL para servicio de Usuarios
  quizdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - quizdb-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  quizdb-data:

networks:
  app-network:
    driver: bridge